name: Test CPU actions

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
      - name: test cpu cores
        run: echo ${{ steps.cpu-cores.outputs.count }}
